global:
  scrape_interval: 5s


alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 192.168.0.108:9093

rule_files:
  - "alert.rules.yml"
  

scrape_configs:
  - job_name: 'openwrt_collectd'
    #metrics_path: /metrics
    static_configs:
      - targets: 
        - 192.168.0.2:9100

  - job_name: "windowshost"
    metrics_path: /metrics
    static_configs:
      - targets:
        - 192.168.0.105:9182
        - 192.168.0.112:9182


  - job_name: "labprometehus"
    metrics_path: /metrics
    static_configs:
      - targets: 
        - 192.168.0.108:9100
       
  - job_name: "gitlabexporter"
    metrics_path: /metrics
    static_configs:
      - targets:
        - 192.168.0.119:9100


  - job_name: nginx
    static_configs:
      - targets:
        - 192.168.0.119:8060
  - job_name: redis
    static_configs:
      - targets:
        - 192.168.0.119:9121
  - job_name: postgres
    static_configs:
      - targets:
        - 192.168.0.119:9187
  - job_name: node
    static_configs:
      - targets:
        - 192.168.0.119:9100
  - job_name: gitlab-workhorse
    static_configs:
      - targets:
        - 192.168.0.119:9229
  - job_name: gitlab-rails
    metrics_path: "/-/metrics"
    scheme: http
    static_configs:
      - targets:
        - 192.168.0.119:80
  - job_name: gitlab-sidekiq
    static_configs:
      - targets:
        - 192.168.0.119:8082
  - job_name: gitlab_exporter_database
    metrics_path: "/database"
    static_configs:
      - targets:
        - 192.168.0.119:9168
  - job_name: gitlab_exporter_sidekiq
    metrics_path: "/sidekiq"
    static_configs:
      - targets:
        - 192.168.0.119:9168
  - job_name: gitaly
    static_configs:
      - targets:
        - 192.168.0.119:9236
  - job_name: registry
    static_configs:
      - targets:
        - 192.168.0.119:5001
